### ISSUE TITLE
Segmentation fault: 11 with missing init

### ISSUE THREAD

**Issue by warlycologne** [practicalswift/swift-compiler-crashes#108] opened 2016-07-30 14:36 UTC
when using generic views without adding init() method to subclass the compiler crashes with segmentation fault 11. the following code does not compile and crashes source kit when default init is not present

```
class View<ContentView: UIView>: UIView {
//    convenience init() {
//        self.init(frame: .zero)
//    }
    override init(frame: CGRect) {
        super.init(frame: frame)
    }
}

let view: View<UILabel> = View()
```

**Comment by practicalswift** [comment] 2016-11-11 20:12
Sorry for my late reply. I cannot reproduce this using `swiftc` compiled against current `master`, so I'm closing this for now.

**Closed by practicalswift** 2016-11-11 20:12 UTC
